spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        id.new_generator_mappings: false
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password: sa

  data:
    rest:
      base-path: /api
      return-body-on-create: true

      #  h2:
      #    console:
      #      enabled: true
      #      path: /h2-console

      # Jackson Serialization Issue Resolver
      #  jackson:
      #    visibility:
      #      field: any
      #      getter: none
      #      is-getter: none
      #      setter: none

  #  https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#security-properties
#  security:
#    user:
#      name: user
#      password: password
#      roles: USER


logging:
  level:
    root: WARN
    ru.javaops.bootjava: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG





