spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        id.new_generator_mappings: false
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password: sa

  data:
    rest:
      base-path: /api
      return-body-on-create: true


#  h2:
#    console:
#      enabled: true
#      path: /h2-console

